{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- $fullName := include "castlemock.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-castlemock
  labels:
  {{include "castlemock.labels" . | nindent 4 }}

  {{- with .Values.persistence.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}